name: Compiling

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Compile
      uses: Ruochenfu2011/compilation@v1
      
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: ./build/libs
    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    # - name: Publish to GitHub Packages
    #   run: ./gradlew publish
    #   env:
    #     USERNAME: ${{ github.actor }}
    #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
